### ISSUE TITLE
Consider using git clone with `--depth`

### ISSUE THREAD

**Issue by schnittstabil** [SamVerschueren/dev-time#6]
From [git-clone docs](https://git-scm.com/docs/git-clone):

> --depth &lt;depth&gt;
> Create a shallow clone with a history truncated to the specified number of revisions.

**Comment by SamVerschueren** [comment]
Good idea. Just wondering what I should use as `--depth` value. Just providing `1` won't do it because maybe it wasn't the user you are looking for that did the latest commit. So what is a good value then? Or should we start with `10`, if the user isn't present in the last `10` commits, just do it again with no `--depth` value.

**Comment by schnittstabil** [comment]
> Just providing 1 won't do it because maybe it wasn't the user you are looking for that did the latest commit.

True.

I'm not familiar enough with the github api, but can't this all be done without cloning? E.g. the [PushEvent commit payload](https://developer.github.com/v3/activity/events/types/#pushevent) resp. the [Commits API](https://developer.github.com/v3/repos/commits/)?

**Comment by SamVerschueren** [comment]
Have to look into this again. At the time I wrote this it didn't seem possible because the timezone information wasn't provided by the GitHub API. But when looking in the docs now, it seems it should be possible. So maybe they added some extra stuff.

Original discussion: https://github.com/sindresorhus/module-requests/issues/47

**Comment by schnittstabil** [comment]
> it seems it should be possible.

Unfortunately, it is not, the example payload of a PushEvent is from a webhook delivery and differ from the Events API payload. Also the Commit API doesn't provide an accurate commit timestamp.

**Comment by SamVerschueren** [comment]
Ah ok, good catch. I wondered if I missed something back when I created it, seems I didn't :). Thanks for the effort of looking into it.

**Comment by eush77** [comment]
Just ran into this issue:

``` ruby
$ dev-time indutny
Error: Command failed: git clone --template="" https://github.com/indutny/io.js.git /tmp/17543cc2-d9f0-4f41-8a25-163762e8a4d9
Cloning into '/tmp/17543cc2-d9f0-4f41-8a25-163762e8a4d9'...
warning: templates not found ""
error: unable to write file test/simple/test-crypto-domains.js
error: unable to write file test/simple/test-crypto-ecb.js
# ...snip...
error: unable to create file test/simple/test-zlib-dictionary.js (No space left on device)
error: unable to create file test/simple/test-zlib-flush.js (No space left on device)
error: unable to create file test/simple/test-zlib-from-gzip.js (No space left on device)
error: unable to create file test/simple/test-zlib-from-multiple-gzip-with-garbage.js (No space left on device)
error: unable to create file test/simple/test-zlib-from-multiple-gzip.js (No space left on device)
error: unable to create file test/simple/test-zlib-from-multiple-huge-gzip.js (No space left on device)
> 153543
```

So yeah, I have no free space for Node.js in tmpfs :smile: 

Maybe we could at least avoid checking out all the files?
